### ISSUE TITLE
0 target skill

### ISSUE THREAD

**Issue by PoloxDisc** [toastygm/HarnMaster-3-FoundryVTT#195] opened 2020-12-23 17:43 UTC
Hello. I bought a foundry vtt at Christmas discount and the first thing I did was install the harnmaster. However, when creating a character for a player, it turned out that his target skill is 0. Just in case, I deactivated the modules because I thought they might be a problem, but it wasn't. I'm sending screenshots, maybe I did something wrong
![image](https://user-images.githubusercontent.com/28192518/103023721-cb916080-454e-11eb-8965-0ca8b17c9e27.png)
![image](https://user-images.githubusercontent.com/28192518/103023631-9c7aef00-454e-11eb-9540-7d7976d8a2b2.png)
![image](https://user-images.githubusercontent.com/28192518/103023650-a7358400-454e-11eb-9fbf-dd9c021fadbd.png)
![image](https://user-images.githubusercontent.com/28192518/103023660-ac92ce80-454e-11eb-9d40-c244bd573972.png)

**Comment by scooper4711** [comment] 2020-12-23 17:59
This looks similar to #190 which we have tracked down to be an incompatibility between Foundry 0.7.9 and the HM module.
A fix has been identified and is slated for the next release, but that's not yet scheduled because of the scope of other features.
Can you download version 0.7.8 and try with that?

**Comment by scooper4711** [comment] 2020-12-23 18:04
to download a previous version, just log in to foundryvtt.com, click on your name, click on purchased software licenses, then edit the URL for the download of your choice and change 0.7.9 to 0.7.8

**Comment by PoloxDisc** [comment] 2020-12-23 18:39
Version 0.7.8:
![image](https://user-images.githubusercontent.com/28192518/103027544-5c1f6f00-4556-11eb-8992-b9b47f222354.png)
Should I wait for update? I wanted play a session on Tuesday for my friend's birthday

**Comment by toastygm** [comment] 2020-12-23 20:39
Just want to be clear.  @scooper4711 meant Foundry Version 0.7.8.  If the problem is still occurring with Foundry 0.7.8, then it will probably be fixed in the next version, planned for this weekend.

There was a change in Foundry v0.7.9 that caused this sort of error, and my next version will be correcting for that.

**Comment by scooper4711** [comment] 2020-12-23 20:43
Well, looks like the target is correctly set there in his most recent screenshot. So my recommendation for @PoloxDisc is to stay on 0.7.8 version of Foundry for the Tuesday b-day party with 1.04 version of HM system.
When the fix for Foundry 0.7.9 is ready, we'll close this issue and others.
The fixes in 0.7.9 version of Foundry VTT are minor. I personally have rolled back to 0.7.8 for my game. 0.7.8 is pretty stable.

**Comment by scooper4711** [comment] 2020-12-23 20:44
(p.s - I too have a game scheduled for Tuesday, and plan on running Foundry 0.7.8 and HM 1.0.4 for it)

**Comment by scooper4711** [comment] 2020-12-31 05:09
@PoloxDisc - please test again with version 1.1.0 which was released today. Note that 1.1.0 requires version 0.7.9 of foundry (or rather, it wasn't tested on 0.7.8)

**Comment by toastygm** [comment] 2021-01-15 19:12
This was fixed in version 1.1.0

**Closed by toastygm** 2021-01-15 19:12 UTC
