### ISSUE TITLE
Compatibility with DF Manual Rolls

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#268] opened 2021-07-02 17:31 UTC
HM3 is mostly compatible with [DF Manual Rolls](https://foundryvtt.com/packages/df-manual-rolls) for people who prefer to bring their own dice (or once Pixels comes out).

This enhancement request is to track dice rolls which don't appear to use the new 0.8 async dice rolling API and therefore don't allow manual rolls.

Note also that this module will vastly assist in testing.

Dice rolls found so far that don't support DF Manual Rolls
 * Injury location

Further, there is the option to flag dice rolls as manual rolls. That feature doesn't appear to be working.

**Comment by toastygm** [comment] 2021-07-10 17:06
I'm not sure what you mean by this:

"Further, there is the option to flag dice rolls as manual rolls. That feature doesn't appear to be working."

Is this a feature of DF Manual Rolls?  If so, that is probably a bug for them.

**Comment by toastygm** [comment] 2021-07-10 17:34
The only random element to the "Injury Roll" is the location.  This is not a roll; it uses a random number generator to randomly determine which hit location to use.  This is why it does not work with DF Manual Rolls.  Note that Foundry VTT has a limitation that no dice may have more than 999 sides, and this makes it unacceptable to use for location specification where locations weights are by default 1-1000 (and can be even higher in some situations).

For "assisted combat", where you actually click on the "Injury" button, a dialog box pops up where you can manually specify a number of parameters, such as aim, impact, and the actual Injury location (it defaults to "Random", and if left at "Random" will then randomly determine the hit location).

For "automated combat" (initiated from the chat card), this dialog is not used since most of the values (e.g., aim and impact) are known.  Also, I felt popping up the injury  dialog box at this point for the edge case of wanting to specify the hit location manually was undesirable.

To gain the effect you are looking for (the edge case of wanting to specify Injury Location manually), the solution is to not use the "Calculate Injury" button on the chat card, but instead use the "Injury" button on the character sheet.  It will then prompt you for the aim, impact, and location, and you can specify the location manually instead of relying on the random number generator.

If you wish, you may submit a separate feature request where instead of generating a random number, I prompt for the random number.  But that will be a separate feature request.

I am closing this request since there is a workaround and this functionality is as designed.

**Closed by toastygm** 2021-07-10 17:34 UTC
