### ISSUE TITLE
Dragging Save K'nor skill from Std Skills-Religion

### ISSUE THREAD

**Issue by Slithkanter** [toastygm/HarnMaster-3-FoundryVTT#224] opened 2021-01-19 02:39 UTC
Dragging the Save K'nor skill from Std Skills-Religion to a character sheets causes the skill to appear in the CraftSkills section of the character sheet instead of the Ritual Skills section of the character sheet.  The other Religion skills populate as expected.

Version: 1.1.3

[SaveKnor_ss.pdf](https://github.com/toastygm/HarnMaster-3-FoundryVTT/files/5833298/SaveKnor_ss.pdf)

**Comment by scooper4711** [comment] 2021-01-19 03:40
That's because those Save K'nor clerics are so crafty. 😆

**Comment by scooper4711** [comment] 2021-01-19 03:43
Kidding aside, as a workaround, if you press the pencil/paper icon for the skill, you can correct the type.

**Comment by Slithkanter** [comment] 2021-01-19 03:56
No doubt! This is nit - small thing easy workaround. The only reason I found it was because the NPC I was creating just happened to have the Save K'nor ritual skill.

**Comment by scooper4711** [comment] 2021-01-19 03:58
I think it's awesome that the module is so stable that we can make these nit bug reports!

**Comment by toastygm** [comment] 2021-05-25 19:53
Fixed in 1.2.8

**Closed** 2021-05-25 23:34 UTC

**Comment by scooper4711** [comment] 2021-05-26 02:12
Confirmed fixed
