### ISSUE TITLE
Automated Combat:  Outnumbered modifiers

### ISSUE THREAD

**Issue by mrg67** [toastygm/HarnMaster-3-FoundryVTT#227] opened 2021-01-30 18:39 UTC
HM3, page COMBAT 11 defines the rules for modifying combat skill roles based on being Outnumbered.

OUTNUMBERED: A character is outnumbered if exclusively engaged by two or more opponents. When counting opponents for this purpose, prone enemies are excluded, as are enemies who are themselves engaged by other friendly characters. Outnumbered characters may attack one opponent during their turn, but if they win a Tactical Advantage, may attack another outnumbering opponent.  **Outnumbered characters may defend against all attacks made on them during their opponents’ turns. However, the EML for any defense (including counterattack) is decreased by ten (10) for each enemy above one.** That is, a character outnumbered 3:1 subtracts 20 from EML for all defense rolls. Outnumbering is ignored for all attacks
(except counterattacks).

The Automated Combat tool currently only allows the ATTACKER to enter any sort of skill test modifier.
![image](https://user-images.githubusercontent.com/74210758/106364810-9f53c700-62e6-11eb-9881-1b7a065fad4c.png)

Once the "Attack" button is clicked in the dialog, the Chat window goes directly to the Defender's options, with no provision for entering any negative modifier for the defender for being outnumbered.

I can see 2 possible ways to enable this:

1.  Allow the ATTACKER in their dialog to enter the DEFENDER's modifier into their dialog box.
2.  Create a new DEFENDER dialog box for entry before the dice are rolled.

Option 1 has the advantage of not needing to create a whole new step in the combat flow, but it puts the onus on Attacker.

Note that this would also enable the negative modifier for the a situation where one of the combatants is Prone.  If the defender is being attacked by a Prone attacker, the defender should increase their chosen Defend type with a +20 modifier.

**Comment by toastygm** [comment] 2021-01-30 22:18
I will have to think about this a bit; I don't really like having the attacker enter in the defender's modifier, and at the same time I am not keen about adding yet another dialog box, especially when 99% of the time it will not be used.

I think the best solution is to use an Effect for this.  On the defender, create a new effect called "Outnumbered", and set the "Melee Defense" to -20 (in this case).  This will provide the effect you are looking for.

This is not a perfect solution.  If a third attacker were to join the fray, you would have to modify the effect to be -30.  But at the same time, if the value is in a dialog box, you will have to simply keep entering it again and again every time there is a defense.  So, maybe the Effect is the best way to handle it.

Note that this modifies the DML directly, so it won't help in the CS case.  For the CS, you will still need to enter in the "bonus" (a negative value).  But there is a place for that in the CS Attack dialog box.

Once you are no longer outnumbered, simply disable the Effect.

**Comment by mrg67** [comment] 2021-01-30 22:37
When you say to use an Effect, are you talking about the Effects tab on the Actor sheet?  I haven't used these yet, so I'm not sure if I set it up correctly.

![image](https://user-images.githubusercontent.com/74210758/106369666-3c732780-6308-11eb-82cd-d9817ee3d139.png)

It didn't seem to have any "effect" in this case.  The defender chose Dodge, and the Effective DML was still at 70, while with a -20 modifier, it should have been at 50.

Also, it would be a pain to have to set-up every actor and NPC with a full range of Outnumbered Effects ahead of time.  Can effects be saved in a compendium, like skills can?

**Comment by mrg67** [comment] 2021-01-30 22:44
I just realized you MAY have meant one of THESE status effects.
![image](https://user-images.githubusercontent.com/74210758/106369803-477a8780-6309-11eb-8533-e415f8e13fb8.png)

In a hex basemap situation, in order to fully cover all of the Outnumbered possibilities, there would have to be 5 status effect icons:  2:1, 3:1, 4:1, 5:1, 6:1

**Comment by toastygm** [comment] 2021-01-30 23:00
No, I meant the "Effects" tab.  When you activate a Melee Defense effect, it should immediately reduce the DML of all melee attacks by the value you set.  So if the DML is normally 70, after turning on the Effect the DML should show as 50.

Yes, this would have to be done on each defender who is outnumbered.  If you have a whole party of people who are outnumbered, this might become unwieldy.

The problem is that there is no really good solution here.  The Effect mechanism lets you set the effect and it remains until you turn it off.  But you have to keep the effect up to date, which can be a pain in a fluid, constantly changing battle.

On the other hand, having a new dialog box that pops up all the time to the defender, that almost always is 0, is going to be annoying as well.  As is having to constantly type in -20, -20, -20 each time it pops up for a person with 3 opponents.

Let me think more on it, but for now the Effect will be the best solution.

Let me know if the DML is in fact not decreasing when you turn on the effect.  That would be a bug.

**Comment by toastygm** [comment] 2021-01-30 23:07
> When you say to use an Effect, are you talking about the Effects tab on the Actor sheet? I haven't used these yet, so I'm not sure if I set it up correctly.
> 
> ![image](https://user-images.githubusercontent.com/74210758/106369666-3c732780-6308-11eb-82cd-d9817ee3d139.png)
> 
> It didn't seem to have any "effect" in this case. The defender chose Dodge, and the Effective DML was still at 70, while with a -20 modifier, it should have been at 50.
> 
> Also, it would be a pain to have to set-up every actor and NPC with a full range of Outnumbered Effects ahead of time. Can effects be saved in a compendium, like skills can?

Yes, you can associate an Effect with any item.  For example, you could create a Trait, and associate an Effect with that trait.  When you add the trait to your character, the effect would be applied too.

Or, you can attach an Effect to a skill, a spell, or a weapon.  When you add that to the character, the effect comes with it.

For this purpose, probably easiest to either associated it with a 0-weight Misc Gear or with a Trait.

**Comment by mrg67** [comment] 2021-01-31 00:29
The effect does not seem to be working.  Can you verify that I defined it correctly?  If the Attribute Key is "Melee Defense" does that apply to any of the defender's choices on the attack results chat selection?

![image](https://user-images.githubusercontent.com/74210758/106371349-43099b00-6318-11eb-9d8a-ab0dce95d24d.png)

**Comment by toastygm** [comment] 2021-01-31 00:45
Yes, you are doing it correctly.  Try this:
Disable all of the Effects.  Go take a look at the Combat tab, any of your melee weapons, the DML.  Note that value.
Then, enable one of the effects, for example "Outnumbered 3:1".  Now, go to the Combat tab and note the DML.  It should have reduced by the value you specified.

It will not show up as a modifier in the chat, it is just that the Eff. DML will be decreased to the appropriate value.

**Comment by mrg67** [comment] 2021-01-31 00:49
It's working for weapon DML, but not for Dodge.

**Comment by toastygm** [comment] 2021-01-31 00:55
Yes, well, Dodge is not a melee weapon, which is why it is not affecting it.  Let me think on that.

**Comment by toastygm** [comment] 2021-01-31 00:57
BTW, for conversations like these, it is much better if we can do them on the Discord. That way everyone else gets the benefit of the discussion.

**Comment by mrg67** [comment] 2021-01-31 00:58
You are right.  Good call.

**Comment by toastygm** [comment] 2021-01-31 01:07
Ok, here's my suggestion: use Fatigue.  I know, it's a hack, and it is purely a workaround.  But by increasing fatigue, you increase PP which should affect all the combat skills.  For those you **don't** want it to effect, just add it back in using the attack bonuses.

Yes, I totally realize what a hack this is, but it is a workaround until I can think of how to implement something like this better.

**Comment by scooper4711** [comment] 2021-05-23 03:54
With the new AE of 0.8.x, I think this could work. However, putting in an AE of -10 on "Melee Defense" should also impact counterstrike, which it currently doesn't.

**Comment by toastygm** [comment] 2021-05-25 20:59
I am implementing a new effect, "outnumbered", in 1.2.8 that should manage this.  This effect will track the number of opponents who outnumber you.  So if you have 3 opponents exclusively engaged with you in combat, then this effect should be set to 3.

I will then calculate the appropriate modifier and apply it during combat.  In the case of block and counterstrike, it will be included as a default "Additional Modifier", and for dodge it will be directly added to the DML.

**Closed** 2021-05-25 23:34 UTC

**Comment by scooper4711** [comment] 2021-05-26 02:12
Confirmed fixed
