### ISSUE TITLE
Creatures can't have condition skill

### ISSUE THREAD

**Issue by scooper4711** [toastygm/HarnMaster-3-FoundryVTT#307] opened 2021-09-05 02:00 UTC
Create a creature, or import one
Try to add the Condition skill.
```
Uncaught (in promise) TypeError: Cannot read property 'toObject' of undefined
[No packages detected]
    at HarnMasterCreatureSheet._onDropItem (foundry.js:24728)
_onDropItem @ foundry.js:24728
```

**Comment by toastygm** [comment] 2021-09-05 14:32
Although I agree it shouldn't throw an error, should a creature be able to have the "Condition" skill?  Like a horse or a lion?  I would think the Condition skill would apply only to humanoids.  Otherwise, I would expect it to be a standard skill of all creatures.

Note that the problem here most likely is the special case code for Condition that is causing the problem; creatures and characters have some subtle differences in what is calculated, so this is undoubtedly causing the issue.

**Comment by scooper4711** [comment] 2021-09-05 14:53
This came from a confusion on my part about endurance and me wanting to have consistency for all actors for combat. Endurance is perfectly fine for creatures. It does limit the GM's ability to make a tougher version of a creature without changing the stats. But that's such an edge case that it's not that important.

**Comment by toastygm** [comment] 2021-09-05 15:39
Two things:

1. I am going to leave this bug open, because no matter what it should not throw an error when you put in the Condition skill.  That is a bug, and that will definitely be fixed.
2. Creatures have a concept of "Load Rating"; this represents the amount of weight they can carry before the encumbrance calculations even come into play.  I have a feeling this may be where the problem is occurring.

I agree that if you want to make a tougher version of a creature, you should probably either increase its stats or maybe add an active effect to modify endurance only.

**Comment by toastygm** [comment] 2021-09-18 18:35
I can't reproduce this bug exactly.  I took your creature, "Count Mule-aca", and attempted to drag the Condition skill from the Physical Skills compendium over.  The Condition skill showed up as expected.  I did not get the error you mentioned.  Can you ensure you can repeat this error?

**Comment by toastygm** [comment] 2021-09-18 18:40
In further reviewing the code, looks like Condition is handled the same for Creatures as for Characters.  So it should operate correctly.  I am going to close this defect; if you can provide details of how to reproduce, it can be reopened.

**Closed by toastygm** 2021-09-18 18:40 UTC
Labels: bug
